export const SET_SELECTED_CITY = 'SET_SELECTED_CITY';
export const ADD_FAVORITE_CITY = 'ADD_FAVORITE_CITY';
export const DELETE_FAVORITE_CITY = 'DELETE_FAVORITE_CITY';
export const SET_WEATHER_DATA = 'SET_WEATHER_DATA';
export const SET_WEATHER_DATA_FORECAST = 'SET_WEATHER_DATA_FORECAST';





